name: PR-Check

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Installing dependencies
        run: npm install -f

      - name: linting
        run: npm run lint

      - name: TypeChecking
        run: npm run test:t
