name: github-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Installing dependencies
        run: npm install -f
      
      - name: Creating .env file
        run: |
          cat << EOF >> .env
          VITE_API_KEY: ${{ secrets.VITE_API_KEY}}
          VITE_API_URL: ${{secrets.VITE_API_URL}}
          EOF

      - name: Building App
        run: npm run build
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
